ACCESS_TOKEN = 'your fb access token'
VERIFY_TOKEN = 'fb verify token'
API_AI_ACCESS_TOKEN = 'api.ai access token'
ZOMATO_API_KEY = 'zomato api key'
FACTS_SOURCE_FILE = 'data/facts.json'
JOKES_SOURCE_FILE = 'data/jokes.json'
QUOTES_SOURCE_FILE = 'data/quotes.json'
